on:
  push:
    branches:
      - master
  pull_request:

name: C.I. Platforms

jobs:
  release_assets:
    name: Check ${{ matrix.config.target }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # Linux
          - { os: ubuntu-latest, cross: false,  test: true,  toolchain: stable, target: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: x86_64-unknown-linux-musl }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: aarch64-unknown-linux-gnu }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: armv7-unknown-linux-gnueabihf }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: mips64el-unknown-linux-gnuabi64 }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: powerpc64le-unknown-linux-gnu }
          # Android
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: aarch64-linux-android }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: armv7-linux-androideabi }
          - { os: ubuntu-latest, cross: true,   test: true,  toolchain: stable, target: x86_64-linux-android }
          # tumbv7neon not yet supported
          # - { os: ubuntu-latest, cross: true,   test: true, toolchain: stable, target: thumbv7neon-linux-androideabi }
          # Macos
          #
          # OS and Architecture supported in local build only, not on github actions
          # - { os: macos-latest, cross: false,   test: true,  toolchain: stable, target: aarch64-apple-darwin }
          - { os: macos-latest, cross: false,   test: true,  toolchain: stable, target: x86_64-apple-darwin }
          # iOS
          - { os: macos-latest, cross: false,   test: false, toolchain: stable, target: aarch64-apple-ios }
          - { os: macos-latest, cross: false,   test: false, toolchain: stable, target: x86_64-apple-ios }
          # Windows
          - { os: windows-latest, cross: false, test: true,  toolchain: stable-x86_64-pc-windows-gnu, target: x86_64-pc-windows-gnu }
          - { os: windows-latest, cross: false, test: true,  toolchain: stable-x86_64-pc-windows-msvc, target: x86_64-pc-windows-msvc }

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.config.toolchain }}
          target: ${{ matrix.config.target }}
          override: true
          default: true

      - name: Downgrade cross
        uses: actions-rs/cargo@v1
        if: ${{ matrix.config.cross }}
        with:
          command: install
          args: --version 0.1.16 cross

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build library (release)
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.config.cross }}
          command: rustc
          args: --release --target ${{ matrix.config.target }} -- -C lto

      - name: Test library (release)
        uses: actions-rs/cargo@v1
        if: ${{ matrix.config.test }}
        with:
          use-cross: ${{ matrix.config.cross }}
          command: test
          args: --release --target ${{ matrix.config.target }}